##############################################
#--------------------------------------------#
#---- Coloured Player List Configuration ----#
#--------------------------------------------#
##############################################

# Adds two dots to the end of a name that is too long
# (cuts name 4 characters shorter instead of 2 characters shorter)
Add Dots: true

# Amount of server ticks it will take for the list to refresh
# (there is 20 ticks in a second)
Update Interval: 20